export { apiRequest, ApiError } from './client';
export * from './types';
export * from './services/bienes.service';
export * from './services/vehiculos.service';
export * from './services/parcelas.service';
export * from './services/propiedades.service';
export * from './services/documentos-propiedad.service';
export * from './services/protocolos.service';
export * from './services/desincorporaciones.service';
export * from './services/compromisos.service';
export * from './services/sedes.service';
export * from './services/departamentos.service';
export * from './services/responsables.service';
export * from './services/almacenes.service';
export * from './services/categorias.service';
export * from './services/documentos.service';
export * from './services/cementerio.service';
